@startuml
start
:User requests deposit address;
if (Is user's wallet in whitelist?) then (yes)
    :Allocate address from HD wallet;
    :Send deposit address to user;
else (no)
    :Notify rejection due to whitelist;
    stop
endif

:User deposits USDT to address;
note right: Wait for Ethereum block generation;

repeat
    :Scheduler requests latest block transactions from Ethereum blockchain;
    :Get list of allocated addresses from database;
    :Filter transactions to allocated addresses;
    repeat :For each Transaction in block
        if (Is transaction to allocated address?) then (yes)
            if (Is USDT transfer amount sufficient?) then (yes)
                :Notify user of successful deposit;
                stop
            else (no)
                :Notify user of insufficient deposit;
                stop
            endif
        endif
    repeat while (More transactions?)
repeat while (Continue monitoring?)
stop
@enduml
