@startuml
skinparam monochrome true

actor Owner
actor DepositWallet as DW

rectangle "Ethereum Network" {
    node "MasterWalletManager" {
        [Constructor] --> Owner: Initialize
        [addDepositWallet] --> Owner: Add Deposit Wallet
        [removeDepositWallet] --> Owner: Remove Deposit Wallet
        [transferAllToMasterWallet] --> Owner: Transfer All to Master
        [transferFromDepositWallet] --> Owner: Transfer from Specific Deposit
    }

    rectangle "ERC20 Token Contract" {
        [transferFrom]
    }
}

Owner -> MasterWalletManager: Deploy contract\n(tokenAddress, masterWallet)

Owner -> MasterWalletManager: addDepositWallet(depositWallet)

Owner -> MasterWalletManager: removeDepositWallet(depositWallet)

Owner -> MasterWalletManager: transferAllToMasterWallet(amount)
'MasterWalletManager -> ERC20 Token Contract: transferFrom(depositWallet, masterWallet, amount)

Owner -> MasterWalletManager: transferFromDepositWallet(depositWallet, amount)
'MasterWalletManager -> ERC20 Token Contract: transferFrom(depositWallet, masterWallet, amount)

@enduml
