@startuml
!define RECTANGLE class
skinparam class {
    BackgroundColor<<Branch>> Gold
    BackgroundColor<<Extension>> LightGreen
    BackgroundColor<<Leaf>> LightBlue
}

RECTANGLE BranchNode <<Branch>> {
  0-9a-f : [Child Nodes]
  Value : null
}

RECTANGLE ExtensionNode <<Extension>> {
  Path : "doge"
  Next : LeafNode
}

RECTANGLE LeafNode <<Leaf>> {
  Path : "coin"
  Value : "crypto"
}

BranchNode : "Root"
'BranchNode -[hidden]-> ExtensionNode
'BranchNode -[hidden]-> LeafNode
'ExtensionNode -[hidden]-> LeafNode
BranchNode --> ExtensionNode
BranchNode --> LeafNode
ExtensionNode --> LeafNode

@enduml
