@startuml
!define primary_key(x) <b><color:red><&key> x</color></b>
!define foreign_key(x) <color:blue><&key> x</color>
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>

left to right direction
skinparam roundcorner 5
skinparam shadowing false
skinparam handwritten false
skinparam class {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}

title 'Crypto Payments Service ERD


table( transaction_receipt ) {
    primary_key( client_code ) : varchar(50)
    column( status ): varchar(1)
    column( transactionHash ): varchar(255)
    column( transactionIndex ): varchar(10)
    column( blockHash ): varchar(255)
    column( blockNumber ): varchar(10)
    column( contractAddress ): varchar(100)
    column( cumulativeGasUsed ): int
    column( gasUsed ): int
    column( created_at ) : datetime
    column( updated_at ) : datetime
}


table( ethereum_deposit_transactions ) {
    primary_key( id ) : bigint
    column( txhash ) : varchar(66)
    column( from_address ) : varchar(42)
    column( to_address ) : varchar(42)
    column( block_number ) : int
    column( coin ) : varchar(10)
    column( amounts ) : decimal(16,8)
    column( client_code ) : varchar(30)
    column( blkhash ) : varchar(50)
    column( is_sended ) : varchar(1)
    column( usd_price ) : decimal(20,2)
    column( krw_price ) : decimal(20,8)
    column( created_at ) : datetime
    column( updated_at ) : datetime
}


table( ethereum_withdraw_transactions ) {
    primary_key( id ) : bigint
    column( txhash ) : varchar(66)
    column( to_address ) : varchar(42)
    column( speed ) : double(3,2)
    column( coin ) : varchar(10)
    column( amounts ) : decimal(16,8)
    column( client_code ) : varchar(30)
    column( blkhash ) : varchar(50)
    column( usd_price ) : decimal(20,2)
    column( fee ) : decimal(12,8)
    column( created_at ) : datetime
}



@enduml
