@startuml
!define primary_key(x) <b><color:red><&key> x</color></b>
!define foreign_key(x) <color:blue><&key> x</color>
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>

left to right direction
skinparam roundcorner 5
skinparam shadowing false
skinparam handwritten false
skinparam class {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}

title 'Gangnam Blockchain Deposit Service ERD

table( transaction_receipt ) {
    primary_key( client_code ) : varchar(50)
    column( status ): varchar(1)
    column( transactionHash ): varchar(255)
    column( transactionIndex ): varchar(10)
    column( blockHash ): varchar(255)
    column( blockNumber ): varchar(10)
    column( contractAddress ): varchar(100)
    column( cumulativeGasUsed ): int
    column( gasUsed ): int
    column( created_at ) : datetime
    column( updated_at ) : datetime
}

table( member ) {
    primary_key( id ) : bigint
    column( user_name ): varchar(30)
    column( user_pass ): varchar(100)
    column( email ): varchar(50)
    column( client_code ): varchar(30)
    column( member_type): varchar(1)
    column( created_at ) : datetime
    column( updated_at ) : datetime
}

table( member_login_log ) {
    primary_key( id ) : bigint
    foreign_key( member_id ): varchar(30)
    column( c_ip ): varchar(300)
    column( c_mobile ): varchar(1)
    column( c_platform ): varchar(30)
    column( c_device ): varchar(30)
    column( created_at ) : datetime
}

@enduml
