@startuml
package "System Roles" {
    component "Super Admin" as Super_Admin {
        note top of "Super_Admin"
            - Delegates administrator roles
            - Edits, creates, disables, enables, and deletes operator, administrator, and user accounts
            - Oversees all system operations
            - Can change their own account’s password
            - Can reset passwords for operators and administrator accounts
        end note
    }

    component "Administrator" {
        note top of "Administrator"
            - Manages assets and operators
            - Edits, creates, disables, enables, and deletes operator and user accounts
            - Can change their own account’s password
            - Can reset passwords for operators and administrator accounts
        end note
    }

    component "Operator" {
        note top of "Operator"
            - Manages system operations
            - Edits, creates, disables, enables, and deletes user accounts
            - Can change their own account’s password
        end note
    }
}

Super_Admin --> Administrator : Designates
Administrator -----> Operator : Manages
Super_Admin --> Operator : Designates
Administrator --> User : Manages
Operator --> User : Manages

'Super_Admin --> Super_Admin : Change own password
'Super_Admin --> Administrator : Reset password
'Super_Admin --> Operator : Reset password

'Administrator --> Administrator : Change own password
'Administrator --> Operator : Reset password

'Operator --> Operator : Change own password
@enduml
